// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("scanr-net")]
[assembly: AssemblyProductAttribute("scanr-net")]
[assembly: AssemblyDescriptionAttribute("A .NET client API for ScanR")]
[assembly: AssemblyVersionAttribute("0.1.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.1.0";
        internal const string InformationalVersion = "0.1.1.0";
    }
}
